CI: Only require MSRV-check to succeed with `-Zminimal-versions`
One of our dependencies recently bumped its `rust-version` causing our
MSRV test to _break again_.  It is undesired to randomly work around
this by bumping our MSRV, or consistently have PRs/merges fail for
unrelated reasons.

Instead, perform the MSRV-test with `-Zminimal-versions`.  This seems
to be generally accepted in the Rust ecosystem (as there is otherwise
no way for crates to bump MSRV barring a semver-breaking release) and
prevents us from hitting unnecessary MSRV build failures caused by
dependencies.

At the same time our minimal version bounds are now exercised, ensuring
downstream crates depending on the `ndk` can build with
`-Zminimal-versions` too - which required specifying a few patch bounds
for our dependencies.

Unfortunately GitHub's UI for `continue-on-error: true` doesn't make it
obvious that a step/job really didn't succeed, this is only visible from
the annotations.  Still, it is relevant to keep track of whether our
non-`minimal-versions` build adheres to MSRV.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -38,17 +38,30 @@ jobs:
         run: cargo check -p ndk-sys --all-targets --all-features --target aarch64-linux-android
 
   check_msrv:
+    strategy:
+      matrix:
+        minimal-versions: [true, false]
     name: Check overall MSRV (1.66.0)
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
+
+      - uses: dtolnay/rust-toolchain@nightly
+        if: ${{ matrix.minimal-versions }}
+
+      - name: Generate lockfile with minimal dependency versions
+        run: cargo +nightly generate-lockfile -Zminimal-versions
+        if: ${{ matrix.minimal-versions }}
 
       - uses: dtolnay/rust-toolchain@1.66.0
         with:
           target: aarch64-linux-android
 
       - name: cargo check
-        run: cargo check --workspace --all-targets --all-features --target aarch64-linux-android
+        run: >
+          cargo check --workspace --all-targets --all-features --target aarch64-linux-android
+          || (echo "::warning::MSRV test failed for minimal-versions: ${{ matrix.minimal-versions }}"; false)
+        continue-on-error: ${{ !matrix.minimal-versions }}
 
   build:
     strategy:
